# Generated by Django 4.2.8 on 2023-12-04 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0010_remove_recipe_difficulty'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='_difficulty',
            field=models.CharField(blank=True, editable=False, max_length=50, null=True),
        ),
    ]
